import type {
  Assumptions,
  ComparisonDelta,
  ComparisonMode,
  ComparisonResult,
  ComparisonSlot,
  ModelResults,
  SensitivityCell,
} from '../types'
import { BASE_RESULTS, getFixture, normalizeTicker } from './data'

const delay = (ms: number) => new Promise((r) => setTimeout(r, ms))

export async function mockAnalyze(ticker: string) {
  await delay(800)
  return getFixture(ticker)
}

function clamp(n: number, min: number, max: number) {
  return Math.min(max, Math.max(min, n))
}

/**
 * Elastic mock engine — starts from fixture base IRR/MOIC/score and nudges
 * with simple assumption deltas so the UI feels interactive without a real LBO.
 */
export function deriveResults(
  ticker: string,
  assumptions: Assumptions,
  companyName: string,
): ModelResults {
  const t = normalizeTicker(ticker)
  const base = BASE_RESULTS[t] ?? BASE_RESULTS.AAPL

  const dLev = assumptions.leverageMultiple - 5.5
  const dEntry = assumptions.entryMultiple - 8.0
  const dExit = assumptions.exitMultiple - assumptions.entryMultiple
  const dGrowth = assumptions.revenueGrowth - 0.05
  const dMargin = assumptions.ebitdaMargin - 0.3
  const dRate = assumptions.interestRate - 0.08
  const dExitYear = assumptions.exitYear - 5

  // Leverage amplifies equity returns; higher entry multiple compresses them
  let moic =
    base.moic +
    dLev * 0.55 -
    dEntry * 0.18 +
    dExit * 0.22 +
    dGrowth * 4 +
    dMargin * 3 -
    dRate * 2
  moic = clamp(moic, 0.6, 6.5)

  const years = Math.max(1, assumptions.exitYear)
  // Align with sensitivity simplification: MOIC^(1/n) - 1, then blend toward base IRR
  const simplifiedIrr = Math.pow(moic, 1 / years) - 1
  let irr = simplifiedIrr + dExitYear * -0.005
  irr = clamp(irr, -0.2, 0.65)

  const f = base.feasibility
  const irrPts = irr <= 0 ? 0 : irr < 0.1 ? (irr / 0.1) * 5 : irr < 0.25 ? 5 + ((irr - 0.1) / 0.15) * 25 : 30
  const moicPts = moic < 1 ? 0 : moic < 3 ? ((moic - 1) / 2) * 20 : 20
  const debtService = clamp(f.debtService - dLev * 2.2 + dMargin * 15, 0, 25)
  const levRed = clamp(f.leverageReduction + dLev * -1.5 + dGrowth * 20, 0, 15)
  const dataQuality = f.dataQuality

  const total = Math.round(
    clamp(irrPts, 0, 30) +
      clamp(moicPts, 0, 20) +
      debtService +
      levRed +
      dataQuality,
  )

  const feasibility = {
    total,
    irr: Math.round(clamp(irrPts, 0, 30) * 10) / 10,
    moic: Math.round(clamp(moicPts, 0, 20) * 10) / 10,
    debtService: Math.round(debtService * 10) / 10,
    leverageReduction: Math.round(levRed * 10) / 10,
    dataQuality,
    max: f.max,
  }

  const exitEquityValue = base.exitEquityValue * (moic / base.moic)

  const reportMarkdown = buildMockReport(companyName, t, assumptions, {
    irr,
    moic,
    feasibility,
    exitEquityValue,
    reportMarkdown: '',
  })

  return {
    irr,
    moic,
    feasibility,
    exitEquityValue,
    reportMarkdown,
  }
}

function buildMockReport(
  name: string,
  ticker: string,
  a: Assumptions,
  r: ModelResults,
): string {
  const irrPct = (r.irr * 100).toFixed(1)
  const moic = r.moic.toFixed(2)
  return [
    `# LBO Narrative — ${name} (${ticker})`,
    ``,
    `*Demo shell report — not generated by an LLM.*`,
    ``,
    `## Deal Summary`,
    `Entry at **${a.entryMultiple.toFixed(1)}x** EV/EBITDA with **${a.leverageMultiple.toFixed(1)}x** leverage,`,
    `exit in year **${a.exitYear}** at **${a.exitMultiple.toFixed(1)}x**.`,
    ``,
    `## Headline Returns`,
    `- IRR: **${irrPct}%**`,
    `- MOIC: **${moic}x**`,
    `- Feasibility Score: **${r.feasibility.total}/100**`,
    ``,
    `## Score Breakdown`,
    `- IRR vs hurdle: ${r.feasibility.irr}/${r.feasibility.max.irr}`,
    `- MOIC: ${r.feasibility.moic}/${r.feasibility.max.moic}`,
    `- Debt service: ${r.feasibility.debtService}/${r.feasibility.max.debtService}`,
    `- Leverage reduction: ${r.feasibility.leverageReduction}/${r.feasibility.max.leverageReduction}`,
    `- Data quality: ${r.feasibility.dataQuality}/${r.feasibility.max.dataQuality}`,
    ``,
    `## Verdict`,
    r.feasibility.total >= 70
      ? `Capital structure looks feasible under these assumptions — returns clear typical PE hurdles with adequate coverage headroom.`
      : r.feasibility.total >= 50
        ? `Mixed feasibility — returns are in a workable range but coverage or data quality softens the overall score.`
        : `Weak feasibility under these assumptions — returns and/or debt service leave limited margin of safety.`,
  ].join('\n')
}

export async function mockGenerate(
  ticker: string,
  assumptions: Assumptions,
  companyName: string,
): Promise<ModelResults> {
  await delay(600)
  return deriveResults(ticker, assumptions, companyName)
}

export function buildSensitivityGrid(
  assumptions: Assumptions,
  baseMoic: number,
): SensitivityCell[] {
  const baseEntry = assumptions.entryMultiple
  const baseExit = assumptions.exitMultiple
  const years = Math.max(1, assumptions.exitYear)
  const entrySteps = [-2, -1, 0, 1, 2].map((d) => +(baseEntry + d * 0.5).toFixed(1))
  const exitSteps = [-2, -1, 0, 1, 2].map((d) => +(baseExit + d * 0.5).toFixed(1))

  const cells: SensitivityCell[] = []
  for (const exit of exitSteps) {
    for (const entry of entrySteps) {
      const moic = clamp(
        baseMoic - (entry - baseEntry) * 0.2 + (exit - baseExit) * 0.25,
        0.5,
        8,
      )
      const irr = Math.pow(moic, 1 / years) - 1
      cells.push({
        entryMultiple: entry,
        exitMultiple: exit,
        moic,
        irr,
        isBase: entry === baseEntry && exit === baseExit,
      })
    }
  }
  return cells
}

export function compareSlots(
  a: ComparisonSlot,
  b: ComparisonSlot,
): ComparisonResult {
  const mode: ComparisonMode = a.ticker === b.ticker ? 'scenario' : 'company'
  const pct = (n: number) => `${(n * 100).toFixed(1)}%`
  const x = (n: number) => `${n.toFixed(2)}x`

  const deltas: ComparisonDelta[] = [
    {
      metric: 'IRR',
      valueA: pct(a.results.irr),
      valueB: pct(b.results.irr),
      change: `${(((b.results.irr - a.results.irr) * 100)).toFixed(1)} pp`,
    },
    {
      metric: 'MOIC',
      valueA: x(a.results.moic),
      valueB: x(b.results.moic),
      change: x(b.results.moic - a.results.moic),
    },
    {
      metric: 'Feasibility',
      valueA: `${a.results.feasibility.total}`,
      valueB: `${b.results.feasibility.total}`,
      change: `${b.results.feasibility.total - a.results.feasibility.total > 0 ? '+' : ''}${b.results.feasibility.total - a.results.feasibility.total}`,
    },
    {
      metric: 'Entry Multiple',
      valueA: x(a.assumptions.entryMultiple),
      valueB: x(b.assumptions.entryMultiple),
      change: x(b.assumptions.entryMultiple - a.assumptions.entryMultiple),
    },
    {
      metric: 'Leverage',
      valueA: x(a.assumptions.leverageMultiple),
      valueB: x(b.assumptions.leverageMultiple),
      change: x(b.assumptions.leverageMultiple - a.assumptions.leverageMultiple),
    },
  ]

  return { mode, deltas, commentary: null }
}

export function mockCommentary(
  mode: ComparisonMode,
  deltas: ComparisonDelta[],
): string {
  const irr = deltas.find((d) => d.metric === 'IRR')
  const moic = deltas.find((d) => d.metric === 'MOIC')
  const lev = deltas.find((d) => d.metric === 'Leverage')
  if (mode === 'scenario') {
    return [
      `Scenario comparison (demo commentary):`,
      `IRR moved ${irr?.change ?? 'n/a'} and MOIC moved ${moic?.change ?? 'n/a'}.`,
      lev && lev.change !== '0.00x'
        ? `Leverage changed by ${lev.change}, which is consistent with the equity-return delta under higher/lower sponsor equity.`
        : `Leverage is unchanged between scenarios; other assumption deltas drive the output difference.`,
    ].join(' ')
  }
  return [
    `Company comparison (demo commentary):`,
    `Side-by-side, IRR is ${irr?.valueA} vs ${irr?.valueB} and MOIC is ${moic?.valueA} vs ${moic?.valueB}.`,
    `This is a descriptive delta only — not a recommendation.`,
  ].join(' ')
}
